import { Video, VideoData } from "@/types/video";

export const mockVideos: Video[] = [
  {
    id: "1",
    thumbnail: "/thumbnails/video1.jpg",
    title: "How to Learn Python Fast - Complete Beginner Guide 2024",
    views: 1200000,
    uploaded: "3 days ago",
    channel: "CodeWithMe",
    channelAvatar: "/avatars/codewithme.jpg",
    duration: "12:34",
    verified: true,
  },
  {
    id: "2",
    thumbnail: "/thumbnails/video2.jpg",
    title: "Top 10 AI Tools You Should Know in 2024 | Game Changers",
    views: 3250000,
    uploaded: "2 days ago",
    channel: "TechVision",
    channelAvatar: "/avatars/techvision.jpg",
    duration: "15:42",
    verified: true,
  },
  {
    id: "3",
    thumbnail: "/thumbnails/video3.jpg",
    title: "React 18 New Features Explained | Complete Tutorial",
    views: 850000,
    uploaded: "1 week ago",
    channel: "WebDev Pro",
    channelAvatar: "/avatars/webdevpro.jpg",
    duration: "8:56",
    verified: false,
  },
  {
    id: "4",
    thumbnail: "/thumbnails/video4.jpg",
    title: "Building a Full Stack App with Next.js and TypeScript",
    views: 2100000,
    uploaded: "5 days ago",
    channel: "FullStack Academy",
    channelAvatar: "/avatars/fullstack.jpg",
    duration: "24:18",
    verified: true,
  },
  {
    id: "5",
    thumbnail: "/thumbnails/video5.jpg",
    title: "Machine Learning Basics Everyone Should Understand",
    views: 1750000,
    uploaded: "1 day ago",
    channel: "AI Explained",
    channelAvatar: "/avatars/aiexplained.jpg",
    duration: "18:27",
    verified: true,
  },
  {
    id: "6",
    thumbnail: "/thumbnails/video6.jpg",
    title: "CSS Grid vs Flexbox - When to Use What?",
    views: 920000,
    uploaded: "4 days ago",
    channel: "CSS Masters",
    channelAvatar: "/avatars/cssmasters.jpg",
    duration: "11:33",
    verified: false,
  },
  {
    id: "7",
    thumbnail: "/thumbnails/video7.jpg",
    title: "Docker Tutorial for Beginners | DevOps Made Easy",
    views: 1430000,
    uploaded: "6 days ago",
    channel: "DevOps Hub",
    channelAvatar: "/avatars/devopshub.jpg",
    duration: "22:15",
    verified: true,
  },
  {
    id: "8",
    thumbnail: "/thumbnails/video8.jpg",
    title: "JavaScript ES2024 Features You Must Know",
    views: 680000,
    uploaded: "2 weeks ago",
    channel: "JS Central",
    channelAvatar: "/avatars/jscentral.jpg",
    duration: "14:09",
    verified: false,
  },
  {
    id: "9",
    thumbnail: "/thumbnails/video9.jpg",
    title: "Building REST APIs with Node.js and Express",
    views: 1560000,
    uploaded: "1 week ago",
    channel: "Backend Basics",
    channelAvatar: "/avatars/backendbasics.jpg",
    duration: "19:44",
    verified: true,
  },
  {
    id: "10",
    thumbnail: "/thumbnails/video10.jpg",
    title: "Database Design Fundamentals | MySQL & PostgreSQL",
    views: 2890000,
    uploaded: "3 weeks ago",
    channel: "Database Pro",
    channelAvatar: "/avatars/databasepro.jpg",
    duration: "26:52",
    verified: true,
  },
];

export const mockVideoData: VideoData = {
  title: "Top 10 AI Tools You Should Know in 2024 | Game Changers",
  views: 3250000,
  likes: 94000,
  uploaded: "2 days ago",
  channel: "TechVision",
  subscribers: 620000,
};
